##
# memory_block.rb
# Created April, 2017
# By Ron Bowes
#
# See: LICENSE.md
#
# Represents a memory layout as a series of multi-byte entries with associated
# data.
##
module H2gb
  module Vault
    class Memory
      class MemoryBlock
        def initialize(raw:, revision:0)
          @raw = raw
          @memory = {}
          @xrefs = {}

          @raw.bytes().each_with_index() do |_, index|
            @memory[index] = {
              revision: revision,
              entry: nil,
            }
          end
        end

        def insert(entry:, revision:)
          entry.each_address() do |i|
            if @memory[i][:entry]
              raise(H2gb::Vault::Memory::MemoryError, "Tried to write to memory that's already in use")
            end
            if @raw[i].nil?
              raise(H2gb::Vault::Memory::MemoryError, "Tried to create an entry outside of the memory range")
            end

            @memory[i] = {
              revision: revision,
              entry: entry,
            }
          end

          # Create cross-references for the entry's references
          entry.refs.each do |ref|
            @xrefs[ref] = @xrefs[ref] || []
            @xrefs[ref] << entry.address

            # Mark the target of the xref as 'updated', so it'll show up when since: is used
            @memory[ref][:revision] = revision
          end
        end

        def delete(entry:, revision:)
          # Delete any xrefs generated by this entry
          entry.refs.each do |i|
            @xrefs[i].delete(entry.address)
          end

          entry.each_address() do |i|
            if @memory[i][:entry].nil?
              raise(H2gb::Vault::Memory::MemoryError, "Tried to clear memory that's not in use")
            end

            @memory[i] = {
              revision: revision,
              entry: nil,
            }

          end

          # Mark the target of the xref as 'updated', so it'll show up when since: is used
          entry.refs.each do |ref|
            @memory[ref][:revision] = revision
          end
        end

        def _get_raw(entry:)
          return @raw[entry.address, entry.length].bytes()
        end

        def _get_entry(address:)
          entry = @memory[address][:entry]

          xrefs = []
          if entry
            entry.each_address() do |this_address|
              xrefs += (@xrefs[this_address] || [])
            end
          else
            xrefs += (@xrefs[address] || [])
          end

          return entry, xrefs.uniq().sort()
        end

        def each_entry_in_range(address:, length:, since: 0)
          i = address

          while i < address + length
            if @memory[i].nil?
              raise(H2gb::Vault::Memory::MemoryError, "Tried to retrieve an entry outside of the range")
            end

            entry, xrefs = _get_entry(address: i)
            revision = @memory[i][:revision]

            if entry
              # Pre-compute the next value of i, in case we're deleting the memory
              next_i = entry.address + entry.length

              if revision > since
                yield(entry.address, entry, _get_raw(entry: entry), xrefs)
              end

              i = next_i
            else
              if revision > since
                yield(i, nil, [@raw[i].ord], xrefs)
              end

              i += 1
            end
          end
        end

        def to_s()
          return (@memory.map() { |m, e| e.to_s() }).join("\n")
        end
      end
    end
  end
end
