##
# memory_block.rb
# Created April, 2017
# By Ron Bowes
#
# See: LICENSE.md
#
# Represents a memory layout as a series of multi-byte entries with associated
# data.
##
module H2gb
  module Vault
    class Memory
      class MemoryBlock
        attr_reader :raw

        def initialize(raw:, revision:0)
          @raw = raw
          @memory = {}
          @code_xrefs = {}
          @data_xrefs = {}
          @last_revision = -1

          @raw.bytes().each_with_index() do |_, index|
            @memory[index] = {
              revision: revision,
              entry: nil,
            }
          end
        end

        private
        def _set_refs_for(refs:, address:, revision:)
          xrefs = {}
          refs.each do |ref|
            if @memory[ref].nil?
              raise(MemoryError, "Reference to an invalid address!")
            end

            xrefs[ref] = xrefs[ref] || []
            xrefs[ref] << address

            # Mark the target of the xref as 'updated', so it'll show up when since: is used
            @memory[ref][:revision] = revision
          end

          return xrefs
        end

        private
        def _check_revision(revision:)
          # Make sure the revision can never decrement, or weird stuff will happen
          if revision < @last_revision
            raise(MemoryError, "Tried to use a lower revision!")
          end
          @last_revision = revision
        end

        public
        def insert(entry:, revision:)
          _check_revision(revision: revision)

          # Validate before we start making changes
          entry.each_address() do |i|
            if @memory[i].nil?
              raise(MemoryError, "Tried to define an entry that's out of range")
            end
            if @memory[i][:entry]
              raise(MemoryError, "Tried to re-define an entry")
            end
          end
          entry.code_refs.each() do |i|
            if @memory[i].nil?
              raise(MemoryError, "Tried to define an invalid code_ref")
            end
          end
          entry.data_refs.each() do |i|
            if @memory[i].nil?
              raise(MemoryError, "Tried to define an invalid data_ref")
            end
          end

          entry.each_address() do |i|
            @memory[i] = {
              revision: revision,
              entry: entry,
            }
          end

          # Create cross-references for the entry's references
          @code_xrefs = _set_refs_for(refs: entry.code_refs, address: entry.address, revision: revision)
          @data_xrefs = _set_refs_for(refs: entry.data_refs, address: entry.address, revision: revision)
        end

        def delete(entry:, revision:)
          _check_revision(revision: revision)

          # Validate before we start making changes
          entry.each_address() do |i|
            if @memory[i][:entry].nil?
              raise(MemoryError, "Tried to clear memory that's not in use")
            end
          end


          # Delete any xrefs generated by this entry
          entry.code_refs.each do |i|
            @code_xrefs[i].delete(entry.address)
          end
          entry.data_refs.each do |i|
            @data_xrefs[i].delete(entry.address)
          end

          entry.each_address() do |i|
            @memory[i] = {
              revision: revision,
              entry: nil,
            }

          end

          # Mark the target of the xref as 'updated', so it'll show up when since: is used
          entry.code_refs.each do |ref|
            @memory[ref][:revision] = revision
          end
          entry.data_refs.each do |ref|
            @memory[ref][:revision] = revision
          end
        end

        def _get_raw(entry:)
          return @raw[entry.address, entry.length].bytes()
        end

        def _get_entry(address:, include_undefined: true)
          if @memory[address].nil?
            raise(MemoryError, "Tried to retrieve an entry outside of the range")
          end
          entry = @memory[address][:entry]

          # Make sure that we always have an entry to work from
          if entry.nil?
            if !include_undefined
              return nil, nil, nil
            end

            entry = MemoryEntry.new(
              address: address,
              type: :uint8_t,
              value: @raw[address].ord(),
              length: 1,
              code_refs: [],
              data_refs: [],
              user_defined: {},
              comment: nil,
            )
          end

          return entry, @code_xrefs[address] || [], @data_xrefs[address] || []
        end

        # TODO: Do a proper test for include_undefined
        def each_entry_in_range(address:, length:, since: 0, include_undefined: true)
          i = address

          while i < address + length
            entry, code_xrefs, data_xrefs = _get_entry(address: i, include_undefined: include_undefined)
            if entry.nil?
              i += 1
              next
            end
            revision = @memory[i][:revision]

            # Pre-compute the next value of i, in case we're deleting the memory
            next_i = entry.address + entry.length

            if revision > since
              yield(entry.address, entry, _get_raw(entry: entry), code_xrefs, data_xrefs)
            end

            i = next_i
          end
        end

        def each_entry(since: 0)
          each_entry_in_range(address: 0, length: @raw.length, since: since) do |address, entry, raw, code_xrefs, data_xrefs|
            yield(address, entry, raw, code_xrefs, data_xrefs)
          end
        end

        def get(address:)
          return _get_entry(address: address)
        end

        def to_s()
          return @memory.to_s()
        end
      end
    end
  end
end
